### PR TITLE
Update to upstream

### PR DESCRIPTION
**Pull request by mlandauer**
This pulls the latest (very big) changes from upstream into here. The biggest thing is that most of the functionality is provided by another project herokuish.

By also upgrading to a much more recent version of herokuish it fixes a long-standing issue with python compiles failing not stopping the rest of the process and getting cached. Very bad!

There are a bunch of changes that had to be made to morph to make everything work this version of buildstep. Most of them have already been merged but there are a few outstanding ones (mostly to do with tests) that are in https://github.com/openaustralia/morph/pull/1047 which should get merged at the same time as this one.

To test out this PR just run `make build` which will create a local copy of the new `openaustralia/buildstep` image.

### CODE REVIEW

**Comment by henare** [comment]
> To test out this PR just run make build which will create a local copy of the new openaustralia/buildstep image.

I've done this and then ran the test suite on the branch from https://github.com/openaustralia/morph/pull/1047 but it doesn't work. What am I doing wrong?

**Comment by mlandauer** [comment]
@henare sounds like you were doing the right thing. When you say "it doesn't work" what exactly do you mean?

**Comment by henare** [comment]
I run the morph test suite and it fails.

**Comment by henare** [comment]
Oh I see you've added a comment about this on that PR: https://github.com/openaustralia/morph/pull/1047#issuecomment-237059630

I assumed that if I built this locally with those instructions and then ran the morph test suite on that branch then it would work because I had the newer version of this installed locally.

I think I've misunderstood. I've cloned this, run `make build` and that works. Is there anything else I should do to test it or are you happy with that?

**Comment by mlandauer** [comment]
@henare see https://github.com/openaustralia/morph/pull/1047#issuecomment-237094241

Could you run the test suite again and add the errors for those here.

I have a suspicion something else might be going on.

**Comment by henare** [comment]
I've updated that morph branch and run the test suite again, this is the output:

```
henare@mana:~/Documents/projects/openaustralia/code/morph rvm:(ruby-2.3.1) git:(small_test_fixes_after_updating_buildstep)$ be rake
/home/henare/.rvm/rubies/ruby-2.3.1/bin/ruby -I/home/henare/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.1/lib:/home/henare/.rvm/gems/ruby-2.3.1/gems/rspec-support-3.5.0/lib /home/henare/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
Run options: exclude {:slow=>true}

Randomized with seed 37318
........................*..............................................................................2016-08-03T02:03:21.660Z 15976 TID-36km4 INFO: Booting Sidekiq 4.1.4 with redis options {:url=>nil}
.....................................................................................*.....F.......F........................................................................................

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) ApiController#run_remote should test streaming
     # No reason given
     # ./spec/controllers/api_controller_spec.rb:79

  2) Morph::DockerRunner should cache the compile
     # No reason given
     # ./spec/lib/morph/docker_runner_spec.rb:230


Failures:

  1) Morph::DockerRunner.compile_and_run should stop if a python compile fails
     Failure/Error: expect(c).to be_nil

       expected: nil
            got: #<Docker::Container:0x00000009a88e88 @id="42eca61dfc52186e906a942fae2d8e6315c832deddf08a0c2755d7c5e7a...=#<Docker::Connection:0x0000000a62b330 @url="unix:///", @options={:socket=>"/var/run/docker.sock"}>>
     # ./spec/lib/morph/docker_runner_spec.rb:36:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:85:in `block (3 levels) in <top (required)>'
     # /home/henare/.rvm/gems/ruby-2.3.1/gems/vcr-3.0.3/lib/vcr.rb:244:in `turned_off'
     # ./spec/spec_helper.rb:83:in `block (2 levels) in <top (required)>'

  2) Morph::DockerRunner.compile_and_run should let me know that it can't select a buildpack
     Failure/Error:
       expect(logs).to eq [
         [:internalout, "Injecting configuration and compiling...\n"],
         [:internalout, "\e[1G       \e[1G-----> Unable to select a buildpack\n"]
       ]

       expected: [[:internalout, "Injecting configuration and compiling...\n"], [:internalout, "\e[1G       \e[1G-----> Unable to select a buildpack\n"]]
            got: [[:internalout, "Injecting configuration and compiling...\n"], [:internalout, "\e[1G-----> Unable to select a buildpack\n"]]

       (compared using ==)

       Diff:
       @@ -1,3 +1,3 @@
        [[:internalout, "Injecting configuration and compiling...\n"],
       - [:internalout, "\e[1G       \e[1G-----> Unable to select a buildpack\n"]]
       + [:internalout, "\e[1G-----> Unable to select a buildpack\n"]]

     # ./spec/lib/morph/docker_runner_spec.rb:25:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:85:in `block (3 levels) in <top (required)>'
     # /home/henare/.rvm/gems/ruby-2.3.1/gems/vcr-3.0.3/lib/vcr.rb:244:in `turned_off'
     # ./spec/spec_helper.rb:83:in `block (2 levels) in <top (required)>'

Finished in 58.31 seconds (files took 6.3 seconds to load)
291 examples, 2 failures, 2 pending

Failed examples:

rspec ./spec/lib/morph/docker_runner_spec.rb:33 # Morph::DockerRunner.compile_and_run should stop if a python compile fails
rspec ./spec/lib/morph/docker_runner_spec.rb:18 # Morph::DockerRunner.compile_and_run should let me know that it can't select a buildpack

Randomized with seed 37318

Coverage report generated for RSpec to /home/henare/Documents/projects/openaustralia/code/morph/coverage. 1368 / 2571 LOC (53.21%) covered.
/home/henare/.rvm/rubies/ruby-2.3.1/bin/ruby -I/home/henare/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.1/lib:/home/henare/.rvm/gems/ruby-2.3.1/gems/rspec-support-3.5.0/lib /home/henare/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
henare@mana:~/Documents/projects/openaustralia/code/morph rvm:(ruby-2.3.1) git:(small_test_fixes_after_updating_buildstep)$ 
```

Here's the images I have:

```
henare@mana:~/Documents/projects/openaustralia/code/morph rvm:(ruby-2.3.1) git:(small_test_fixes_after_updating_buildstep)$ docker images
REPOSITORY                                  TAG                 IMAGE ID            CREATED             SIZE
<none>                                      <none>              c4d628af8211        16 hours ago        1.666 GB
<none>                                      <none>              7c6146985a9e        16 hours ago        1.509 GB
<none>                                      <none>              f12c86b401a3        16 hours ago        1.551 GB
<none>                                      <none>              4191238dc6e0        16 hours ago        1.452 GB
<none>                                      <none>              3ea0b47e210d        16 hours ago        1.514 GB
<none>                                      <none>              f12e0488f4dc        16 hours ago        1.491 GB
<none>                                      <none>              b60a6343cbcd        16 hours ago        1.617 GB
<none>                                      <none>              ded56cb74c0a        16 hours ago        1.617 GB
openaustralia/buildstep                     latest              3809a4f5f977        16 hours ago        1.452 GB
openaustralia/morph-docker-buildstep-base   latest              0f3eb974e9a8        3 months ago        1.437 GB
henare@mana:~/Documents/projects/openaustralia/code/morph rvm:(ruby-2.3.1) git:(small_test_fixes_after_updating_buildstep)$ 
```

**Comment by mlandauer** [comment]
@henare the errors you're getting indicate to me that you've still got the original `openaustralia/buildstep` locally rather than the one made by running `make build` from the PR on the openaustralia/buildstep repo.

Maybe try running `docker rmi openaustralia/buildstep` before you run `make build`?

See if that makes a difference

**Comment by henare** [comment]
I removed all images before I started this. Here's what happened when I did this again:

```
henare@mana:~/Documents/projects/openaustralia/code/morph rvm:(ruby-2.3.1) git:(small_test_fixes_after_updating_buildstep)$ docker rmi openaustralia/buildstep
Untagged: openaustralia/buildstep:latest
henare@mana:~/Documents/projects/openaustralia/code/morph rvm:(ruby-2.3.1) git:(small_test_fixes_after_updating_buildstep)$ 
```

```
henare@mana:~/Desktop/buildstep rvm:(ruby-2.2.0) git:(master)$ make build
docker build -t openaustralia/buildstep .
Sending build context to Docker daemon 508.4 kB
Step 1 : FROM openaustralia/morph-docker-buildstep-base
 ---> 0f3eb974e9a8
Step 2 : MAINTAINER Jeff Lindsay <progrium@gmail.com>
 ---> Using cache
 ---> fcd99fc324b8
Step 3 : ADD ./stack/configs/etc-profile /etc/profile
 ---> Using cache
 ---> aa35e5ab021e
Step 4 : ADD ./builder/ /build
 ---> Using cache
 ---> 7e2e5dae1b91
Step 5 : RUN xargs -L 1 /build/install-buildpack /tmp/buildpacks < /build/config/buildpacks.txt
 ---> Using cache
 ---> 3809a4f5f977
Successfully built 3809a4f5f977
henare@mana:~/Desktop/buildstep rvm:(ruby-2.2.0) git:(master)$ 
```

Sorry I don't really understand this to help debugging.

**Comment by henare** [comment]
@mlandauer spotted the problem - I was running `make build` from the master branch of this repository, not the branch for this pull request! :headdesk:

I've now got a passing test suite. Assigning back to @mlandauer for merge and deploy.

**Pull request merged**
